# Generated by Django 4.1.1 on 2022-09-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='min_max',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_prod', models.IntegerField()),
                ('max_prod', models.IntegerField()),
            ],
        ),
    ]
