# Generated by Django 4.1.1 on 2022-09-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_min_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_prod', models.IntegerField(null=True)),
                ('max_prod', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='min_max',
        ),
    ]
