# Generated by Django 4.0.3 on 2022-04-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('office', models.CharField(max_length=100)),
            ],
        ),
    ]
