# Generated by Django 4.0.3 on 2022-05-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_produto_produtopedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Atendete',
            new_name='Atendente',
        ),
    ]
