# Generated by Django 4.0.3 on 2022-05-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_rename_atendete_pedido_atendente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Catagoria',
            new_name='Categoria',
        ),
    ]
