# Generated by Django 4.0.3 on 2022-05-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_atendente_alter_pedido_estoquista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
