# Generated by Django 4.0.3 on 2022-05-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nr_pedido',
            field=models.IntegerField(null=True),
        ),
    ]
