# Generated by Django 4.1 on 2022-08-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_produtopedido_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Status',
            field=models.CharField(max_length=125),
        ),
    ]
