# Generated by Django 4.1 on 2022-08-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=125)),
            ],
        ),
    ]
