# Generated by Django 4.0.5 on 2022-08-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_data_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=125)),
            ],
        ),
        migrations.DeleteModel(
            name='Data_Status',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.categoria'),
        ),
    ]
