# Generated by Django 4.0.5 on 2022-10-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('pedidos', '0012_categoria_delete_data_status_remove_pedido_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
