# Generated by Django 4.0.5 on 2022-10-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nr_pedido',
            new_name='tp_Pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Estoquista',
        ),
    ]
