# Generated by Django 4.0.5 on 2022-11-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
        ('worker', '0003_worker_usuario'),
        ('pedidos', '0015_pedidoentrada_produtoentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Atendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoria'),
        ),
        migrations.AlterField(
            model_name='pedidoentrada',
            name='Atendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
        migrations.AlterField(
            model_name='pedidoentrada',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoria'),
        ),
        migrations.AlterField(
            model_name='produtoentrada',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidoentrada'),
        ),
        migrations.AlterField(
            model_name='produtoentrada',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
