# Generated by Django 3.1.6 on 2022-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_auto_20221115_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoentrada',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
